[WIP] migrate GraphQL API to Next.js server

diff --git a/packages/web/Dockerfile b/packages/web/Dockerfile
--- a/packages/web/Dockerfile
+++ b/packages/web/Dockerfile
@@ -1,54 +1,77 @@
-#Creates a layer from node:alpine image.
-FROM node:alpine
+FROM node:18-alpine AS base
 
-#Creates directories
-RUN mkdir -p /usr/src/app
+FROM base AS deps
+RUN apk add --no-cache g++ make py3-pip libc6-compat
+WORKDIR /app
 
-RUN apk add --update --no-cache python3 make g++\
-   && rm -rf /var/cache/apk/*
+# Install dependencies based on the preferred package manager
+COPY package.json ./
+COPY package-lock.json ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+# RUN npm install
 
-# COPY start.sh /usr/src/app
-# COPY build.sh /usr/src/app
-# RUN chmod +x /usr/src/app/start.sh /usr/src/app/build.sh
+# START DEV
+FROM base AS dev
 
-#Sets an environment variable
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
 ENV PORT 3000
+# set hostname to localhost
+ENV HOSTNAME "0.0.0.0"
+# ENV DEV
 
-#Sets the working directory for any RUN, CMD, ENTRYPOINT, COPY, and ADD commands
-WORKDIR /usr/src/app
 
-# RUN chmod +x build.sh
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
-#Copy new files or directories into the filesystem of the container
-COPY package.json /usr/src/app
-COPY package-lock.json /usr/src/app
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+ENV NEXT_TELEMETRY_DISABLED 1
 
-#Execute commands in a new layer on top of the current image and commit the results
-RUN npm install
+RUN npm run build
 
-##Copy new files or directories into the filesystem of the container
-COPY . /usr/src/app
-
-# ENV APP_ENV
-ARG NEXT_PUBLIC_APP_ENV
-ENV NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
-# ENV NEXT_PUBLIC_GRAPHQL_API={NEXT_PUBLIC_GRAPHQL_API}
-# ENV NEXT_PUBLIC_GRAPHQL_API_STAGING={NEXT_PUBLIC_GRAPHQL_API_STAGING}
-# ENV NEXT_PUBLIC_GRAPHQL_API_PRODUCTION={NEXT_PUBLIC_GRAPHQL_API_PRODUCTION}
-
-# ARG STAGE=development
-# COPY ./environments/.env.${STAGE}.template .env.production.local
-COPY .env.production .env.production
-COPY .env.development .env.development
-COPY .env.local .env.production
-
-#Execute commands in a new layer on top of the current image and commit the results
+# If using npm comment out above and use below instead
 # RUN npm run build
-RUN chmod 755 build.sh && /usr/src/app/build.sh
-RUN chmod 755 start.sh
 
-#Informs container runtime that the container listens on the specified network ports at runtime
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
 
-#Allows you to configure a container that will run as an executable
-ENTRYPOINT ["/usr/src/app/start.sh"]
+ENV PORT 3000
+# set hostname to localhost
+ENV HOSTNAME "0.0.0.0"
+
+CMD ["node", "server.js"]
